"""
These declarations describe "gmr.contract.v13.0". That string is what a caller
pins to know which shapes they may match on; tools/gate.py fails the build
when this file and the runtime disagree about it.

The version has two segments: v<breaking>.<additive>. The additive segment
moves when an output type gains a variant or an optional field - survivable
by any consumer that keeps a fallback arm in every match over a discriminant,
which is the one rule this surface asks of its readers. The breaking segment
moves when anything is removed, renamed, or re-meant. The same rule holds for
scripts parsing the CLI's --json output.

Values cross as plain dicts/lists shaped exactly like the JSON the node
binding serves — dist/npm/index.d.ts is the field-level reference; this stub
carries the callable surface.
"""

from typing import Any, Optional

CONTRACT: str

class Fault(ValueError):
    """Every refusal and failure, spoken as `<kind>: <message>`.

    kind is a stable snake_case token -- `refused` (the console would not
    parse the ask), `assembly` (the runtime could not be put together),
    `internal`, or a runtime code such as `not_bound`, `no_such_anchor`,
    `no_provider`, `condensed_into_nothing`. Match the token, not the prose.
    """

def open(options: dict[str, Any]) -> Gmr: ...

class Gmr:
    def sample(self, anchor: str, how: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
    def read(self, anchor: str, how: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
    def ground(self, claims: list[str | dict[str, Any]], how: Optional[dict[str, Any]] = None) -> list[dict[str, Any]]: ...
    def since(self, cursor: int, status: Optional[str] = None) -> dict[str, Any]: ...
    def bind(self, claim: str, anchors: list[str], source: str, how: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
    def revoke(self, claim: str, source: str) -> dict[str, Any]: ...
    def link(self, from_: str, to: str, kind: str, source: str) -> None: ...
    def unlink(self, from_: str, to: str, kind: str, source: str, asserted_as: Optional[str] = None) -> int: ...
    def anchors(self) -> list[dict[str, Any]]: ...
    def claims(self) -> list[Any]: ...
    def cobound(self, claim: str) -> list[Any]: ...
    def links(self, record: str) -> dict[str, Any]: ...
    def condense(self, said: str, into: str, source: str) -> dict[str, Any]: ...
    def open(self, request: dict[str, Any]) -> dict[str, Any]: ...
    def close(self, key: str, why: str) -> None: ...
